# Generated by Django 4.2.2 on 2023-09-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0002_researchpaper_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
