# Generated by Django 4.2.2 on 2023-09-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0003_researchpaper_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(max_length=255),
        ),
    ]
