# Generated by Django 4.2.2 on 2023-09-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0004_alter_quizquestion_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], max_length=255),
        ),
    ]
