# Generated by Django 4.2.2 on 2023-09-18 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0007_articles_articlequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlequestion',
            name='research_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HUB.articles'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
